### ISSUE TITLE
Heron viewer on PDOK sometimes fails to load

### ISSUE THREAD

**Issue by justb4** [smartemission/smartemission#120]
Ik krijg af en toe een foutmelding (Chrome en Safari Mac OSX) bij laden van https://pdok.smartemission.nl/heron. Pagina blijft wit. Vooral bij geforceerde refresh (shift reload).

Lijkt volgorde probleem .js files laden. Vreemd is dat ik dit niet kan reproduceren op huidige productie: http://data.smartemission.nl/heron (zelfde Docker Image versie). Deze app is al jaren hetzelfde m.b.t. volgorde/laden .js files in html head en probleem is nooit eerder opgetreden. Enig verschil PDOK en huidige context is dat http://data.smartemission.nl/heron Traefik als frontend proxy heeft en PDOK nginx (via K8s Ingress).

**Comment by justb4** [comment]
Is indeed specific only for the K8s environment. Pinned down to the file `Map.js`, which does not load. Via `curl` the file data is fetched partially and an error appears:

```
curl https://pdok.smartemission.nl/heron/static/config/Map.js

(loads partial Map.js file data)
curl: (18) transfer closed with 32470 bytes remaining to read
```

From some Google searches could be SSL related or the combination `nginx/gunicorn`. 
Also when loading https://pdok.smartemission.nl/heron/static/config/Map.js directly in the browser it fails to load most of the times.

**Comment by justb4** [comment]
Seems to be related to `gunicorn` `eventlet`, at least from logs:

```
[2018-06-06 15:26:27 +0000] [14] [ERROR] Socket error processing request.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/gunicorn/workers/async.py", line 66, in handle
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python2.7/site-packages/gunicorn/workers/async.py", line 56, in handle
    self.handle_request(listener_name, req, client, addr)
  File "/usr/local/lib/python2.7/site-packages/gunicorn/workers/async.py", line 129, in handle_request
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python2.7/site-packages/gunicorn/workers/async.py", line 112, in handle_request
    resp.write_file(respiter)
  File "/usr/local/lib/python2.7/site-packages/gunicorn/http/wsgi.py", line 403, in write_file
    if not self.sendfile(respiter):
  File "/usr/local/lib/python2.7/site-packages/gunicorn/http/wsgi.py", line 393, in sendfile
    sent += sendfile(sockno, fileno, offset + sent, count)
  File "/usr/local/lib/python2.7/site-packages/gunicorn/http/_sendfile.py", line 66, in sendfile
    raise OSError(e, os.strerror(e))
OSError: [Errno 11] Resource temporarily unavailable

```

Maybe the `pip install` for latest versions of `eventlet, gunicorn, flask, requests` and async mode did not workout. Heron 1.0.5 contained these versions:

```
Jinja2-2.10 MarkupSafe-1.0 Werkzeug-0.14.1 certifi-2018.4.16 
chardet-3.0.4 click-6.7 enum34-1.1.6 eventlet-0.23.0 
flask-1.0.2 greenlet-0.4.13 gunicorn-19.8.1 idna-2.6 
itsdangerous-0.24 requests-2.18.4 urllib3-1.22
```

At least for now don't use async workers (`eventlet`) and pin `eventlet, gunicorn, flask, requests` versions.

**Comment by justb4** [comment]
Closing, Heron fixed and upgraded to 1.0.6 tag.
